'use client'

import { useAuth } from '@/hooks/auth'
import GuestNavBar from '@/components/GuestNavBar'

export const metadata = {
    title: process.env.NEXT_APP_NAME,
    description: 'Generated by Next.js',
}

export default function DashboardPagesLayout({ children }) {
    const { user } = useAuth({ middleware: 'auth' })
    return (
        <>
            <GuestNavBar user={user} />
            {children}
        </>
    )
}
